### ISSUE TITLE
SSR in 4.4.0 crashes

### ISSUE THREAD

**Issue by perrin4869** [reactjs/react-transition-group#618]
> What is the current behavior?

Running this module on node.js (for example during ssr) results in: `ReferenceError: Element is not defined`

> What is the expected behavior?

Importing `react-transition-group` does not result in an error

The problem is this line:
https://github.com/reactjs/react-transition-group/blob/c8631587f9e1d18f5161f5490e6f5c225f06c6ae/src/Transition.js#L397

A [possible solution](https://stackoverflow.com/questions/48007326/what-is-the-correct-proptype-for-a-ref-in-react) is: `Element = typeof Element === 'undefined' ? function(){} : Element`

**Comment by RetiFier** [comment]
I too ran through the error exactly two hours ago. We tried getting rid of 'react-transition-group' LMAO! 
Hope it serves as a temporary solution for ongoing development for me personally.
Cheerio!

**Comment by SaravananTamizhan** [comment]
@perrin4869  I do too. I tried commenting out the following code on '/node_modules/react-transition-group/cjs/Transition.js' in line 451.
VERY UNCONVENTIONAL WAY TO SOLVE A PROBLEM!
In case, you in need of any immediate solution, hope it works well for you too.
Would love to know more if a solution is up!

```
  nodeRef: _propTypes.default.shape({
    current: _propTypes.default.instanceOf(Element)
  }),
```

**Comment by oliviertassinari** [comment]
What about supporting callback refs and iframes?

```jsx
PropTypes.oneOfType([PropTypes.func, PropTypes.object])
```

**Comment by helloitsm3** [comment]
Having issues right now after updating my npm packages

**Comment by arrudaricardo** [comment]
Same problem here, using material-ui on nextjs:
```
ReferenceError: Element is not defined
    at Object.<anonymous> (/home/ric/code/anyway/node_modules/react-transition-group/cjs/Transition.js:452:44)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ric/code/anyway/node_modules/react-transition-group/cjs/CSSTransition.js:14:42)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ric/code/anyway/node_modules/react-transition-group/cjs/index.js:6:45)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
```

**Comment by priteshpoddar** [comment]
Is this fixed?

**Comment by abdullah0786** [comment]
> Is this fixed?

i dont think so because version is still 4.4.0.
https://github.com/reactjs/react-transition-group/issues/618

**Comment by furcan** [comment]
+1

**Comment by Krasnodaretc** [comment]
+1

**Comment by abdullah0786** [comment]
> I too ran through the error exactly two hours ago. We tried getting rid of 'react-transition-group' LMAO!
> Hope it serves as a temporary solution for ongoing development for me personally.
> Cheerio!

make it 4.3.0 from 4.4.0 version

**Comment by deividcingolani** [comment]
+1
